### ISSUE TITLE
READMEの分類について

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-121#2]
特許法施行法と同じIssueですが、
READMEの分類は日本法令索引のものを利用します。
http://hourei.ndl.go.jp/SearchSys/viewEnkaku.do?i=3WuzlvXeauubU9%2Fqm4s9pQ%3D%3D

- 産業一般
- 工業所有権
- 特許

です。日本法令索引は改正履歴も見られて便利です

**Comment by Heat-Exchange** [comment]
修正しました。この情報は[ガイドライン](https://github.com/law-of-japan/repository-management-guideline/blob/master/CONTRIBUTING.md)になかったので、追記してプルリクを送っておきます。

**Comment by pinfort** [comment]
確認しました。
