### ISSUE TITLE
附則のタイトルについて

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-121#4]
https://github.com/law-of-japan/19540413-law-122/issues/7#issue-438169074

これと同じです。

# 附則

となっていますが、

# 特許法
## 附則（昭和三四年四月一三日法律第百二十一号）

に変えてください。また、以降の見出し2はそれぞれ見出し3にするようにしてください。

**Comment by pinfort** [comment]
このとき、法令番号を囲む括弧は全角丸括弧にするようにしてください。

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
