### ISSUE TITLE
各ファイル先頭に法令名を

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-121#5]
全てのファイルの一行目に法令名を記述してください。

# 特許法

のようにです。
これに伴って、以降の見出しは大きさを変えるようにしてください。

**Comment by Heat-Exchange** [comment]
修正しました。こちらもガイドラインに追記しようと思います

**Comment by pinfort** [comment]
READMEも、トップのリポジトリ名を削除して法令名をHeadingしてください。

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
