### ISSUE TITLE
各条のArticle captionについて

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/19590413-law-121#8]
第一章、第二章、第三章などにおいて、Article captionで表記法の揺れが見られます。
第五章、第六章はできていますので同じようにしてください。

### 第一条（目的）

などの「目的」の部分です。
これを囲う括弧は全角丸括弧で、「第〇条」の後にスペース等は入れないでください。

**Comment by Heat-Exchange** [comment]
修正しました。

**Comment by pinfort** [comment]
第一条だけが治っていないようです。（半角丸括弧になっています）

**Comment by Heat-Exchange** [comment]
修正しました

**Comment by pinfort** [comment]
確認しました。
